### ISSUE TITLE
[BUG] package-lock.json contain some fixed ip

### ISSUE THREAD

**Issue by GuoPhilipse** [apache/incubator-linkis-website#600]
when we want to execute the `npm install` under the root directory of the website repo,
the error log will be 
`
npm notice Run npm install -g npm@9.1.2 to update!
npm notice 
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://10.107.103.115:8001/yallist/download/yallist-4.0.0.tgz failed, reason: connect ETIMEDOUT 10.107.103.115:8001
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:

after check the dev code, there is some fixed ip in `package-lock.json`. which cannot be connected. not sure if we can change to domain name to let everyone can download . or i have missed sth .

`
    "@types/json-schema": {
      "version": "7.0.9",
      "resolved": "http://10.107.103.115:8001/@types/json-schema/download/@types/json-schema-7.0.9.tgz",
      "integrity": "sha1-l+3JA36gw4WFMgsolk3eOznkZg0="
    }`
`

**Comment by GuoPhilipse** [comment]
have fixed in https://linkis.apache.org/docs/latest/development/build-console, so closing this issue.

**Comment by GuoPhilipse** [comment]
after using the following two steps suggested in the  https://linkis.apache.org/docs/latest/development/build-console,there will be errors when i execute `npm run start`.
`
1、npm install -g cnpm --registry=https://registry.npm.taobao.org
2、cnpm install
`



`philipse@% npm run start

> linkis-web-apache@0.0.1 start
> docusaurus start

[INFO] Starting the development server...
[ERROR] Error: Unrecognized keys community found in preset-classic configuration. The allowed keys are debug, docs, blog, pages, sitemap, theme, googleAnalytics, gtag. Check the documentation: https://docusaurus.io/docs/using-plugins#docusauruspreset-classic for more information on how to configure individual plugins.
    at preset (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_preset-classic@2.2.0@@docusaurus/preset-classic/lib/index.js:55:15)
    at /Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/plugins/presets.js:39:62
    at Array.forEach (<anonymous>)
    at loadPresets (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/plugins/presets.js:25:13)
    at loadPluginConfigs (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/plugins/configs.js:72:52)
    at initPlugins (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/plugins/init.js:42:65)
    at loadPlugins (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/plugins/index.js:26:50)
    at load (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/server/index.js:76:90)
    at async Command.start (/Users/philipse/project/tcproject/incubator-linkis-website/node_modules/_@docusaurus_core@2.2.0@@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.2.0
Node version: v18.4.0`
